name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: './'